port: :8080  # Http server port.
run_mode: debug  # Server running Mode: debug, release, test.
max_ping_count: 10  #  Self check count.
jwt_secret: jg3R67XjEsiwxylpnMS4ICXfc7UWAxwk
tls:
  port: :8081
  cert: conf/server.crt
  key: conf/server.key
log:
  writers: file,stdout
  logger_level: DEBUG
  logger_file: log/login_server.log
  log_format_text: false
  rollingPolicy: size
  log_rotate_date: 1
  log_rotate_size: 1
  log_backup_count: 7
db:
  name: db_login_server
  addr: 127.0.0.1:3306
  username: root
  password: qwe123
docker_db:
  name: db_login_server
  addr: 127.0.0.1:3306
  username: root
  password: qwe123